# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMwQm2GRIZOzcm__5JK8IqH3SvPBGdgj
"""

import streamlit as st
import json
from utils.pdf_utils import extract_text_from_pdf
from utils.image_utils import extract_text_from_image
from utils.parse_utils import simple_parse_cv

st.set_page_config(page_title="AI CV Parser", page_icon="📄", layout="wide")

# UI CSS
st.markdown("""
<style>
html, body, [class*="css"] {
    font-family: 'Segoe UI', sans-serif;
}

.big-title { font-size: 40px; font-weight: 800; text-align: center; color: #2C3E50; }
.subtitle  { font-size: 18px; text-align: center; color: #7F8C8D; margin-bottom: 30px; }
.upload-box { border: 2px dashed #6C5CE7; padding: 25px; border-radius: 15px; background: #F8F9FF; text-align: center; }
.result-card { background: white; padding: 20px; border-radius: 15px; box-shadow: 0 4px 14px rgba(0,0,0,0.1); margin-bottom: 20px; }
.section-title { font-size: 22px; font-weight: 700; color: #6C5CE7; margin-bottom: 10px; }
</style>
""", unsafe_allow_html=True)

st.markdown("<div class='big-title'>📄 AI CV Parser</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Upload your CV and extract structured information instantly</div>", unsafe_allow_html=True)

st.markdown("<div class='upload-box'>", unsafe_allow_html=True)
file = st.file_uploader("Upload CV (PDF / PNG / JPG)", type=["pdf", "png", "jpg", "jpeg"])
st.markdown("</div>", unsafe_allow_html=True)

if file:
    st.success("File uploaded!")

    if st.button("Parse CV"):
        file_bytes = file.read()

        if file.type == "application/pdf":
            raw_text = extract_text_from_pdf(file_bytes)
        else:
            raw_text = extract_text_from_image(file_bytes)

        if not raw_text.strip():
            st.error("Cannot extract text. Try another file.")
            st.stop()

        parsed = simple_parse_cv(raw_text)

        st.subheader("🔍 Extracted Information")

        st.markdown("<div class='result-card'>", unsafe_allow_html=True)
        st.write(parsed)
        st.markdown("</div>", unsafe_allow_html=True)