# -*- coding: utf-8 -*-
"""image_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMwQm2GRIZOzcm__5JK8IqH3SvPBGdgj
"""

from PIL import Image
import pytesseract
import io

def extract_text_from_image(file_bytes):
    image = Image.open(io.BytesIO(file_bytes))
    return pytesseract.image_to_string(image)