# -*- coding: utf-8 -*-
"""pdf_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMwQm2GRIZOzcm__5JK8IqH3SvPBGdgj
"""

import pdfplumber
import io

def extract_text_from_pdf(file_bytes):
    text = ""
    try:
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            for page in pdf.pages:
                text += page.extract_text() + "\n"
    except:
        return ""
    return text